site_name: HCE Staging Docs
site_url: https://chaosnative.github.io/hce-docs-staging
site_description: >-
  Staging area for HCE Enterprise public docs content
repo_name: chaosnative/hce-docs-staging
repo_url: https://github.com/chaosnative/hce-docs-staging
theme: 
  name: material
  custom_dir: overrides
  font:
    text: Work Sans
  highlightjs: true
  logo: images/harness-chaos-engineering.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-off
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-on
        name: Switch to light mode
  hljs_languages:
    - yaml
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.share
    - search.suggest
extra:
  version:
    provider: mike
markdown_extensions:
  - codehilite
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: iter8-tools
      repo: iter8
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
    - Home: index.md
    - User Guide:
      - Contents: placeholder.md
      - Installation: 
        - Kubernetes: placeholder.md
        - OpenShift: placeholder.md
      - Running a Sample Chaos Scenario: placeholder.md
      - Connecting Chaos Delegates: placeholder.md
      - Creating Custom Chaos Scenarios: placeholder.md
      - Defining Hypothesis Using Probes: placeholder.md 
      - Analyzing Chaos Runs: placeholder.md
      - Managing Chaos Projects: placeholder.md 
      - Creating Your Own ChaosHubs: placeholder.md 
      - Managing Chaos Scenarios: placehoder.md
      - Running a Gameday: placeholder.md
      - Including Chaos in Harness Pipeline: placeholder.md 
      - Building Your Own Chaos Experiment: placeholder.com

    - Technical Reference:
      - Chaos Resources:
        - Contents: placeholder.md
        - Platform:
          - Chaos Center: placeholder.md
          - Chaos Delegates: placeholder.md
          - Chaos Experiments: placeholder.md
          - Enterprise Hubs: placeholder.md
          - Hypothesis Validation: placeholder.md
          - Monitoring: placeholder.md

    - Litmus FAQ:
      - FAQ: 
        - Install: placeholder.md 
        - Platform: placeholder.md
        - Experiments: placeholder.md
        - Integrations: placeholder.md
      - Troubleshooting:
        - Install: placeholder.md 
        - Platform: placeholder.md
        - Experiments: placeholder.md
        - Integrations: placeholder.md
