site_name: HCE Staging Docs
site_url: https://chaosnative.github.io/hce-docs-staging
site_description: >-
  Staging area for HCE Enterprise public docs content
repo_name: chaosnative/hce-docs-staging
repo_url: https://github.com/chaosnative/hce-docs-staging
theme: 
  name: material
  custom_dir: overrides
  font:
    text: Work Sans
  highlightjs: true
  logo: images/harness-chaos-engineering.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-off
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-on
        name: Switch to light mode
  hljs_languages:
    - yaml
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.share
    - search.suggest
extra:
  version:
    provider: mike
markdown_extensions:
  - codehilite
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: iter8-tools
      repo: iter8
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
    - Home: index.md
    - HCE Overview: overview/placeholder.md
    - User Guide:
      - Overview: user-guide/overview/placeholder.md
      - Installation: user-guide/installation/kubernetes/placeholder.md
      - Run a Sample Chaos Scenario: user-guide/run-a-sample-chaos-scenario/placeholder.md
      - Connect Chaos Delegates: user-guide/connect-chaos-delegates/placeholder.md
      - Create Custom Chaos Scenarios: user-guide/create-custom-chaos-scenarios/placeholder.md
      - Define Hypothesis Using Probes: user-guide/define-hypothesis-using-probes/placeholder.md 
      - Analyze Chaos Runs: user-guide/analyze-chaos-runs/placeholder.md
      - Manage Chaos Projects: user-guide/manage-chaos-projects/placeholder.md 
      - Manage Chaos Scenarios: user-guide/manage-chaos-scenarios/placehoder.md
      - Run a Gameday: user-guide/run-a-gameday/placeholder.md
      - Upgrade the HCE platform: 
        - Upgrade the Control Plane: user-guide/upgrade-the-hce-platform/control-plane.md
        - Upgrade the Execution Plane: user-guide/upgrade-the-hce-platform/execution-plane.md
      - Cleanup Harness Chaos Installation: 
        - Disconnect Chaos Delegates: user-guide/cleanup-harness-chaos-installation/chaos-delegate-disconnect.md
        - Uninstall HCE platform: user-guide/cleanup-harness-chaos-installation/cleanup-litmus-installation.md 

    - Technical Reference:
      - Contents: technical-reference/content/placeholder.md
      - Platform: 
        - Chaos Center: technical-reference/chaos-center/placeholder.md
        - Chaos Delegates: technical-reference/chaos-delegates/placeholder.md
        - Chaos Experiments: technical-reference/chaos-experiments/placeholder.md
        - Enterprise Hubs: technical-reference/enterprise-hubs/placeholder.md
        - Hypothesis Validation: technical-reference/hypothesis-validation/placeholder.md
        - Monitoring: technical-reference/monitoring/placeholder.md
      - APIs:
        - Chaos Manager: technical-reference/APIs/chaos-manager/placeholder.md

    - HCE FAQ:
      - FAQ: 
        - Install: faq/install/placeholder.md 
        - Platform: faq/platform/placeholder.md
        - Experiments: faq/experiments/placeholder.md
        - Integrations: faq/integrations/placeholder.md
      - Troubleshooting:
        - Install: troubleshooting/install/placeholder.md 
        - Platform: troubleshooting/platform/placeholder.md
        - Experiments: troubleshooting/experiments/placeholder.md
        - Integrations: troubleshooting/integrations/placeholder.md
