site_name: HCE Staging Docs
site_url: https://chaosnative.github.io/hce-docs-staging
site_description: >-
  Staging area for HCE Enterprise public docs content
repo_name: chaosnative/hce-docs-staging
repo_url: https://github.com/chaosnative/hce-docs-staging
theme: 
  name: material
  custom_dir: overrides
  font:
    text: Work Sans
  highlightjs: true
  logo: images/harness-chaos-engineering.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-off
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-on
        name: Switch to light mode
  hljs_languages:
    - yaml
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.share
    - search.suggest
extra:
  version:
    provider: mike
markdown_extensions:
  - codehilite
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: iter8-tools
      repo: iter8
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
    - Home: index.md
    - User Guide:
      - Contents: experiments/categories/contents.md
      - Installation: 
        - Kubernetes: experiments/categories/pods/container-kill.md
        - OpenShift: experiments/categories/kafka/kafka-broker-pod-failure.md
      - First Scenario: experiments/categories/pods/container-kill.md


    - Technical Reference:
      - Chaos Resources:
        - Contents: experiments/concepts/chaos-resources/contents.md
        - Platform:
          - Chaos Center: experiments/concepts/chaos-resources/chaos-engine/contents.md
          - Chaos Delegates: experiments/concepts/chaos-resources/chaos-engine/engine-state.md
          - Experiments: experiments/concepts/chaos-resources/chaos-engine/application-details.md
          - Hypothesis Validation: experiments/concepts/chaos-resources/chaos-engine/rbac-details.md
          - Monitoring: experiments/concepts/chaos-resources/chaos-engine/runtime-details.md

    - Litmus FAQ:
      - FAQ: 
        - Install: experiments/faq/install.md 
        - Platform: experiments/faq/experiments.md
        - Experiments: experiments/faq/portal.md
      - Troubleshooting:
        - Install: experiments/troubleshooting/install.md 
        - Platform: experiments/troubleshooting/experiments.md
        - Experiments: experiments/troubleshooting/portal.md
    - Platform Docs ⧉: https://docs.litmuschaos.io/
    - Releases ⧉: https://github.com/litmuschaos/litmus/releases
