site_name: HCE Staging Docs
site_url: https://chaosnative.github.io/hce-docs-staging
site_description: >-
  Staging area for HCE Enterprise public docs content
repo_name: chaosnative/hce-docs-staging
repo_url: https://github.com/chaosnative/hce-docs-staging
theme: 
  name: material
  custom_dir: overrides
  font:
    text: Work Sans
  highlightjs: true
  logo: images/harness-chaos-engineering.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-off
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-on
        name: Switch to light mode
  hljs_languages:
    - yaml
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.share
    - search.suggest
extra:
  version:
    provider: mike
markdown_extensions:
  - codehilite
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: iter8-tools
      repo: iter8
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
    - Home: index.md
    - User Guide:
      - Contents: user-guide/content/placeholder.md
      - Installation: 
        - Kubernetes: user-guide/installation/kubernetes/placeholder.md
        - OpenShift: user-guide/installation/openshift/placeholder.md
      - Running a Sample Chaos Scenario: user-guide/running-a-sample-chaos-scenario/placeholder.md
      - Connecting Chaos Delegates: user-guide/connecting-chaos-delegates/placeholder.md
      - Creating Custom Chaos Scenarios: user-guide/creating-custom-chaos-scenarios/placeholder.md
      - Defining Hypothesis Using Probes: user-guide/defining-hypothesis-using-probes/placeholder.md 
      - Analyzing Chaos Runs: user-guide/analyzing-chaos-runs/placeholder.md
      - Managing Chaos Projects: user-guide/managing-chaos-projects/placeholder.md 
      - Creating Your Own ChaosHubs: user-guide/creating-your-own-chaoshubs/placeholder.md 
      - Managing Chaos Scenarios: user-guide/managing-chaos-scenarios/placehoder.md
      - Running a Gameday: user-guide/running-a-gameday/placeholder.md
      - Including Chaos in Harness Pipeline: user-guide/including-chaos-in-harness-pipelines/placeholder.md 
      - Building Your Own Chaos Experiment: user-guide/building-your-own-chaos-experiments/placeholder.com
      - Upgrade:
        - Upgrading the Control Plane: user-guide/upgrade/control-plane.md
        - Upgrading the Execution Plane: user-guide/upgrade/execution-plane.md
      - Cleanup: 
        - Disconnecting the Chaos Delegates: user-guide/cleanup/chaos-delegate-disconnect.md
        - Uninstalling Litmus: user-guide/cleanup/cleanup-litmus-installation.md 

    - Technical Reference:
      - Contents: technical-reference/content/placeholder.md
      - Platform: 
        - Chaos Center: technical-reference/chaos-center/placeholder.md
        - Chaos Delegates: technical-reference/chaos-delegates/placeholder.md
        - Chaos Experiments: technical-reference/chaos-experiments/placeholder.md
        - Enterprise Hubs: technical-reference/enterprise-hubs/placeholder.md
        - Hypothesis Validation: technical-reference/hypothesis-validation/placeholder.md
        - Monitoring: technical-reference/monitoring/placeholder.md
      - APIs:
        - Chaos Manager: technical-reference/APIs/chaos-manager/placeholder.md

    - HCE FAQ:
      - FAQ: 
        - Install: faq/install/placeholder.md 
        - Platform: faq/platform/placeholder.md
        - Experiments: faq/experiments/placeholder.md
        - Integrations: faq/integrations/placeholder.md
      - Troubleshooting:
        - Install: troubleshooting/install/placeholder.md 
        - Platform: troubleshooting/platform/placeholder.md
        - Experiments: troubleshooting/experiments/placeholder.md
        - Integrations: troubleshooting/integrations/placeholder.md
